---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-exporter
  namespace: monitoring
  labels:
    app: demo-exporter
spec:
  selector:
    matchLabels:
      app: demo-exporter
  template:
    metadata:
      annotations:
      labels:
        app: demo-exporter
    spec:
      containers:
      - name: demo-exporter
        image: exporter:v1.2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 9877
---
kind: Service
apiVersion: v1
metadata:
  name: demo-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "9877"
spec:
  selector:
    app: demo-exporter
  ports:
    - name: http-metrics
      port: 9877
      targetPort: 9877
      protocol: TCP

      