global:
  scrape_interval:     30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - /prometheus/rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    basic_auth:
      username: 'admin'
      password: 'test'

  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik:8080']

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'demo'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['demo:8080']
      labels:
        hostname: int-prd-vmm-01