apiVersion: 1

deleteDatasources:
- name: Prometheus
  orgId: 1

datasources:
- name: 'prometheus'
  type: 'prometheus'
  orgId: 1
  access: 'proxy'
  url: 'http://prometheus:9090'
  isDefault: true
  editable: false
  basicAuth: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'test'